// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIpcd8ezcc9FTroR36gr4MPCGTE8GOZ5Q',
    appId: '1:442624031928:web:1d785557124d4d34f9484d',
    messagingSenderId: '442624031928',
    projectId: 'zone-interesting',
    authDomain: 'zone-interesting.firebaseapp.com',
    storageBucket: 'zone-interesting.appspot.com',
    measurementId: 'G-CYK8ZSQBV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgly0mSqyBQLI-2RqTtaOoidcjUIJ1fGU',
    appId: '1:442624031928:android:15941c83269b5776f9484d',
    messagingSenderId: '442624031928',
    projectId: 'zone-interesting',
    storageBucket: 'zone-interesting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDTdykxgOrvewiN_HPON003D58NJ3Jtwc',
    appId: '1:442624031928:ios:3cba4442b1fb9c1ff9484d',
    messagingSenderId: '442624031928',
    projectId: 'zone-interesting',
    storageBucket: 'zone-interesting.appspot.com',
    iosBundleId: 'com.example.interestingZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDTdykxgOrvewiN_HPON003D58NJ3Jtwc',
    appId: '1:442624031928:ios:8dda246caf9cec6bf9484d',
    messagingSenderId: '442624031928',
    projectId: 'zone-interesting',
    storageBucket: 'zone-interesting.appspot.com',
    iosBundleId: 'com.example.interestingZone.RunnerTests',
  );
}
